spring:
  application:
    name: api-gateway
  profiles:
    active: development
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    bus:
      enabled: true
      refresh:
        enabled: true
      config:
        fail-fast: true
    gateway:
      routes:
        - id: user-microservice
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/users/**
        - id: booking-microservice
          uri: lb://booking-microservice
          predicates:
            - Path=/api/booking/**
        - id: product-microservice
          uri: lb://product-service
          predicates:
            - Path=/api/products/**, /api/categories/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: house-microservice
          uri: lb://house-microservice
          predicates:
            - Path=/houses/**
        - id: flat-microservice
          uri: lb://flat-microservice
          predicates:
            - Path=/flats/**, /**
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  #logging:
  # level:
  #  '[org.springframework.cloud.gateway]': TRACE

server:
  port: 8079

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

#jwt:
 # secret: testing
  #validity: 20
  #authDisabled: true