spring:
  main:
    web-application-type: reactive
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: user-microservice
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  #logging:
  # level:
  #  '[org.springframework.cloud.gateway]': TRACE

  #jwt:
  # secret: testing
#logging:
 # level:
  #  '[org.springframework.cloud.gateway]': TRACE

#jwt:
 # secret: testing
  #validity: 20
  #authDisabled: true