

spring:

#logging:
 # level:
  #  ROOT: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    fetch-registry: true
    register-with-eureka: true

  logging:
    level:
      com:
        netflix:
          eureka: debug
          discovery: debug

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED



